config/routes.rb
UcbLibrary::Application.routes.draw do

  get "display/main"
  match "display/main" => 'display#main', :as => 'main'

  get "photo/doe"
  match "photo/doe" => 'photo#doe', :as => 'doe'

  get "photo/haas"
  match "photo/haas" => 'photo#haas', :as => 'haas'

  get "photo/hangrove"
  match "photo/hangrove" => 'photo#hangrove', :as => 'hangrove'

  get "photo/kresge"
  match "photo/kresge" => 'photo#kresge', :as => 'kresge'

  get "photo/moffitt"
  match "photo/moffitt" => 'photo#moffitt', :as => 'moffitt'

  get "photo/vlsb"
  match "photo/vlsb" => 'photo#vlsb', :as => 'vlsb'

  get "photo/wurster"
  match "photo/wurster" => 'photo#wurster', :as => 'wurster'

  get "home/proposal"
  match "home/proposal" => 'home#proposal', :as => 'proposal'

  # See how all your routes lay out with "rake routes"

  root :to => 'home#index'
  get "home/index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
  def main
    @file_name = params[:id] + '.jpg'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def proposal
  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def doe
  end

  def haas
  end

  def hangrove
  end

  def kresge
  end

  def moffitt
  end

  def vlsb
  end

  def wurster
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/display/main.html.erb
<center>
	<div class="row-fluid">
		<div class="img-polaroid">
			<%= image_tag @file_name %>
		</div>
	</div>
</center>

<br /><br />	

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />

app/views/home/index.html.erb
<div class="hero-unit">
	<center>
		<h1>Welcome!</h1>
		<br />
		Find out study spaces you never knew existed before
	</center>
</div>

<div class="well">
	<div class="row-fluid">
		<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/doe">
		  		Doe Library
			</a>
		</div>
		<div class="span10">
		  	The Doe/Moffitt Libraries together support the teaching, 
		  	research, and instructional needs affiliated with more than 
		  	fifty academic departments and programs in the Arts and Humanities, 
		  	Social Sciences, International and Area Studies, and Undergraduate Services. 
		  	The Doe/Moffitt collections, services, and programs also serve the broader 
		  	campus community, the public, and an international community of scholars and researchers.
	  	</div>
  	</div>
  	<br /><br />
	<div class="row-fluid">
		<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/haas">
		  		Haas Library
			</a>
		</div>
		<div class="span10">
		  	The Thomas J. Long Business Library houses the major collection of 
		  	business administration materials on the University of California, Berkeley campus. 
		  	Materials are acquired to support the research and teaching mission of the university. 
		  	The field of economics is included in the Doe Memorial Library collection.
	  	</div>
  	</div>
  	<br /><br />
	<div class="row-fluid">
	  	<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/hangrove">
		  		Hangrove Library
			</a>
		</div>
		<div class="span10">
		  	The Jean Gray Hargrove Music Library serves the diverse teaching and research 
		  	needs of the UC Berkeley Department of Music, which offers a general undergraduate 
		  	major and graduate programs in musicology, ethnomusicology, and composition, as well as 
		  	embracing a variety of performance activities.
	  	</div>
  	</div>
  	<br /><br />
  	<div class="row-fluid">
	  	<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/kresge">
		  		Kresge Library
			</a>
		</div>
		<div class="span10">
		  	The services and collection of the Kresge Engineering Library support the research 
		  	and teaching programs of the College of Engineering. The print and electronic collections 
		  	include research materials in the following areas: bioengineering, civil engineering, 
		  	computer science, electrical engineering, environmental engineering, industrial engineering, 
		  	materials science, mechanical engineering, mineral engineering, naval architecture, offshore engineering, 
		  	operations research, and nuclear engineering. [Chemical engineering materials are housed in the Chemistry Library.]
	  	</div>
  	</div>
  	<br /><br />
  	<div class="row-fluid">
	  	<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/moffitt">
		  		Moffitt Library
			</a>
		</div>
		<div class="span10">
		  	A core collection of "best books" in the liberal arts, Moffitt serves a broad campus 
		  	readership of both undergraduates and nonspecialists. Strong in the area of contemporary issues, 
		  	the collection not only supports the undergraduate curriculum of UC Berkeley, 
		  	but also encourages students to educate themselves about the world outside the classroom and 
		  	beyond the scope of their disciplines.
	  	</div>
  	</div>
  	<br /><br />
  	<div class="row-fluid">
	  	<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/vlsb">
		  		VLSB Library
			</a>
		</div>
		<div class="span10">
		  	The Marian Koshland Bioscience and Natural Resources Library provides services 
		  	and collections to support the research and teaching needs of the Departments of Integrative Biology 
		  	and Molecular and Cell Biology within the Division of Biological Sciences 
		  	in the College of Letters and Science; and the Departments of Agricultural and Resource Economics, 
		  	Environmental Science, Policy and Management, Nutritional Sciences and Toxicology, 
		  	and Plant and Microbial Biology within the College of Natural Resources. 
		  	The collection includes materials in bioinformatics, molecular and cell biology, botany, 
		  	environmental science, physiology, ecology, nutrition and food science, plant pathology, soil science, 
		  	entomology, forestry and zoology.
	  	</div>
  	</div>
  	<br /><br />
  	<div class="row-fluid">
	  	<div class="span2">
		  	<a class="btn btn-info btn-block" type="button" href="/photo/wurster">
		  		Wurster Library
			</a>
		</div>
		<div class="span10">
		  	The Environmental Design Library is one of the premier architecture, landscape architecture, 
		  	and city and regional planning libraries in North America. 
		  	The merger of four departmental libraries formed the Library: Architecture, Landscape Architecture, 
		  	City and Regional Planning, and Decorative Arts, formerly Household Arts.
	  	</div>
	</div>
</div>

<br /><br /><br /><br /><br />

<center>
	<strong>Febrianto Djunaidi</strong><br>
	<a href="mailto:#">febrianto5+ph@gmail.com</a>
</center>

<br />

app/views/home/proposal.html.erb
<center>
	<div class="row-fluid">
		<div class="img-polaroid">
			<%= image_tag "proposal.jpg" %>
		</div>
	</div>
</center>

<br /><br />	

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if current_page? (doe_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'Doe', doe_path %>
	</li>
	
  <% if current_page? (haas_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'Haas', haas_path %>
	</li>
	
  <% if current_page? (hangrove_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'Hangrove', hangrove_path %>
	</li>
	
  <% if current_page? (kresge_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'Kresge', kresge_path %>
	</li>
	
  <% if current_page? (moffitt_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'Moffitt', moffitt_path %>
	</li>
	
  <% if current_page? (vlsb_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'VLSB', vlsb_path %>
	</li>
	

	
  <% if current_page? (proposal_path) %>
	<li class="active">
  <% else %>
  	<li>
  <% end %>
		<%= link_to 'Project Proposal', proposal_path %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UCB Library" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/photo/doe.html.erb
<div class="hero-unit">
	<center>
		<h1>Doe Library</h1>
	</center>
</div>

<ul class="thumbnails">
	
	<li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=001" class="thumbnail">
	      <%= image_tag "112.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=002" class="thumbnail">
	      <%= image_tag "113.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=003" class="thumbnail">
	      <%= image_tag "114.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=004" class="thumbnail">
	      <%= image_tag "115.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=005" class="thumbnail">
	      <%= image_tag "116.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=006" class="thumbnail">
	      <%= image_tag "117.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=007" class="thumbnail">
	      <%= image_tag "118.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=008" class="thumbnail">
	      <%= image_tag "119.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=009" class="thumbnail">
	      <%= image_tag "120.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=010" class="thumbnail">
	      <%= image_tag "121.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=011" class="thumbnail">
	      <%= image_tag "122.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=012" class="thumbnail">
	      <%= image_tag "123.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=013" class="thumbnail">
	      <%= image_tag "124.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=014" class="thumbnail">
	      <%= image_tag "125.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=015" class="thumbnail">
	      <%= image_tag "126.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=016" class="thumbnail">
	      <%= image_tag "127.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=017" class="thumbnail">
	      <%= image_tag "128.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=018" class="thumbnail">
	      <%= image_tag "129.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=019" class="thumbnail">
	      <%= image_tag "130.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=020" class="thumbnail">
	      <%= image_tag "131.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=021" class="thumbnail">
	      <%= image_tag "132.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=022" class="thumbnail">
	      <%= image_tag "133.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=023" class="thumbnail">
	      <%= image_tag "134.jpg" %>
	    </a>
	  </li>
  </li>
  
</ul>

<br /><br />

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />

app/views/photo/haas.html.erb
<div class="hero-unit">
	<center>
		<h1>Haas Library</h1>
	</center>
</div>

<ul class="thumbnails">
	
	<li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=024" class="thumbnail">
	      <%= image_tag "135.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=025" class="thumbnail">
	      <%= image_tag "136.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=026" class="thumbnail">
	      <%= image_tag "137.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=027" class="thumbnail">
	      <%= image_tag "138.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=028" class="thumbnail">
	      <%= image_tag "139.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=029" class="thumbnail">
	      <%= image_tag "140.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=030" class="thumbnail">
	      <%= image_tag "141.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=031" class="thumbnail">
	      <%= image_tag "142.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=032" class="thumbnail">
	      <%= image_tag "143.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=033" class="thumbnail">
	      <%= image_tag "144.jpg" %>
	    </a>
	  </li>
  </li>
  
</ul>

<br /><br />

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />

app/views/photo/hangrove.html.erb
<div class="hero-unit">
	<center>
		<h1>Hangrove Library</h1>
	</center>
</div>

<ul class="thumbnails">
	
	<li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=034" class="thumbnail">
	      <%= image_tag "145.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=035" class="thumbnail">
	      <%= image_tag "146.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=036" class="thumbnail">
	      <%= image_tag "147.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=037" class="thumbnail">
	      <%= image_tag "148.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=038" class="thumbnail">
	      <%= image_tag "149.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=039" class="thumbnail">
	      <%= image_tag "150.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=040" class="thumbnail">
	      <%= image_tag "151.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=041" class="thumbnail">
	      <%= image_tag "152.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=042" class="thumbnail">
	      <%= image_tag "153.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=043" class="thumbnail">
	      <%= image_tag "154.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=044" class="thumbnail">
	      <%= image_tag "155.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=045" class="thumbnail">
	      <%= image_tag "156.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=046" class="thumbnail">
	      <%= image_tag "157.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=047" class="thumbnail">
	      <%= image_tag "158.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=048" class="thumbnail">
	      <%= image_tag "159.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=049" class="thumbnail">
	      <%= image_tag "160.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=050" class="thumbnail">
	      <%= image_tag "161.jpg" %>
	    </a>
	  </li>
  </li>
    
</ul>

<br /><br />

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />

app/views/photo/kresge.html.erb
<div class="hero-unit">
	<center>
		<h1>Kresge Library</h1>
	</center>
</div>

<ul class="thumbnails">
	
	<li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=051" class="thumbnail">
	      <%= image_tag "162.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=052" class="thumbnail">
	      <%= image_tag "163.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=053" class="thumbnail">
	      <%= image_tag "164.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=054" class="thumbnail">
	      <%= image_tag "165.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=055" class="thumbnail">
	      <%= image_tag "166.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=056" class="thumbnail">
	      <%= image_tag "167.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=057" class="thumbnail">
	      <%= image_tag "168.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=058" class="thumbnail">
	      <%= image_tag "169.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=059" class="thumbnail">
	      <%= image_tag "170.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=060" class="thumbnail">
	      <%= image_tag "171.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=061" class="thumbnail">
	      <%= image_tag "172.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=062" class="thumbnail">
	      <%= image_tag "173.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=063" class="thumbnail">
	      <%= image_tag "174.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=064" class="thumbnail">
	      <%= image_tag "175.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=065" class="thumbnail">
	      <%= image_tag "176.jpg" %>
	    </a>
	  </li>
  </li>
  
</ul>

<br /><br />

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />

app/views/photo/moffitt.html.erb
<div class="hero-unit">
	<center>
		<h1>Moffitt Library</h1>
	</center>
</div>

<ul class="thumbnails">
	
	<li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=066" class="thumbnail">
	      <%= image_tag "177.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=067" class="thumbnail">
	      <%= image_tag "178.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=068" class="thumbnail">
	      <%= image_tag "179.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=069" class="thumbnail">
	      <%= image_tag "180.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=070" class="thumbnail">
	      <%= image_tag "181.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=071" class="thumbnail">
	      <%= image_tag "182.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=072" class="thumbnail">
	      <%= image_tag "183.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=073" class="thumbnail">
	      <%= image_tag "184.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=074" class="thumbnail">
	      <%= image_tag "185.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=075" class="thumbnail">
	      <%= image_tag "186.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=076" class="thumbnail">
	      <%= image_tag "187.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=077" class="thumbnail">
	      <%= image_tag "188.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=078" class="thumbnail">
	      <%= image_tag "189.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=079" class="thumbnail">
	      <%= image_tag "190.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=080" class="thumbnail">
	      <%= image_tag "191.jpg" %>
	    </a>
	  </li>
	  <li class="span3">
	    <a href="/display/main?id=081" class="thumbnail">
	      <%= image_tag "192.jpg" %>
	    </a>
	  </li>
  </li>
  
  <li class="span12">
	  <li class="span3">
	    <a href="/display/main?id=082" class="thumbnail">
	      <%= image_tag "193.jpg" %>
	    </a>
	  </li>
  </li>
  
</ul>

<br /><br />

<center>
	<div class="row-fluid">
		<input type=button class="btn btn-inverse span1" value= "Back" onclick= "history.back()">
		</input>
	</div>
</center>

<br />